### ISSUE TITLE
Changing to ES2015

### ISSUE THREAD

**Issue by henninglh** [Quist/rating-frontend#2]
Need to add babel in order to get this.
ESlint is also convenient for keeping the code standard nice 'n clean.

**Comment by Quist** [comment]
ah yeah :+1:

**Comment by henninglh** [comment]
ES6 bygger! testing up next

**Comment by Quist** [comment]
Good work :)

2016-01-12 15:58 GMT+01:00 Henning Lund-Hanssen notifications@github.com:

**Comment by Quist** [comment]
Merged, gw @henninglh++
