### ISSUE TITLE
Does not reset "add game" info when adding a game

### ISSUE THREAD

**Issue by aulonm** [Quist/rating-frontend#29]
Hello, yes, I have an issue to report

Try to add a new game, chose the players and who won, then press "add game". The game is added, but the chosen players and who won does not reset. People may get confused and think that the game has not been added and then tries to add it again. 

Thank you in advance, love this app

**Comment by Quist** [comment]
We at rating-frontend want to thank you for your positive review. The app would be nothing without the support from users like you! You're the best! 

Our engineers will get started on this asap. We aim at releasing a fix before May 2017.

Happy squashing!

**Comment by aulonm** [comment]
you're the best\*
