### ISSUE TITLE
Error when attempting to delete an existing game

### ISSUE THREAD

**Issue by Quist** [Quist/rating-frontend#6]
It does not work x(

`Uncaught TypeError: Cannot read property 'props' of null` @ `/Game.jsx line 11`

**Comment by Quist** [comment]
Probably a quick fix, but I'm going to bed right now :8ball:

**Comment by henninglh** [comment]
Fucked up sleep schedule made me look at this on my phone. Dunno if this
will work, but that's what hit me first. In the Game.jsx file, render()
function:

Change:
onClick={this.handleDelete}

To this:
onClick={this.handleDelete.bind(this)}

Alternatively, functions can be bound in the constructor of the class:
this.handleDelete = this.handleDelete.bind(this);

Sleep well!

**Comment by Quist** [comment]
good times
